### ISSUE TITLE
Erreur avec 2 connecteurs

### ISSUE THREAD

**Issue by jachao92** [c-jimenez/open-ocpp-simu#15]
Bonjour,

J'utilise actuellement le simulateur mais j'ai constaté un souci quand je crée un nouveau point de charge avec deux connecteurs ou plus ils sont toujours dans l'état "Unavailable" et je ne peux pas démarrer de transactions. Pour les autres n'ayant qu'un connecteur la connexion est ok avec le central system et tout est fonctionnel.

Merci pour votre retour.

**Comment by c-jimenez** [comment]
Bonjour,

Je viens de tester sur la branche develop (=tag1.1.0 du simulateur + tag1.2.0 de la libopenocpp) et j'arrive bien à créer un chargepoint avec 2 connecteurs qui fonctionne correctement (j'ai essayé avec 4, ça fonctionne aussi):

![image](https://user-images.githubusercontent.com/18682655/223548283-243fb3cb-994e-49ea-bdbb-079a1de1cbb3.png)

J'utilise l'exemple quick_start_central_system comme Central System pour le test.
Quel Central System utilisez vous?

Pouvez-vous m'envoyer la database et la config de votre chargepoint multi-connecteurs qui ne fonctionne pas afin que je regarde un peu la config et les logs?
Ces fichiers sont dans le working directory du launcher (1 répertoire par chargepoint simulé).

**Comment by jachao92** [comment]
Merci pour votre retour. 
Finalement en utilisant les dernières versions mise en ligne, cela fonctionne. Pour informations, j'utilisais un CS en phase de développement.
Désolé de vous avoir dérangé.

**Comment by c-jimenez** [comment]
Bonjour,
Pas de soucis je ferme le ticket, merci d'utiliser le soft!
