### ISSUE TITLE
Démarrage de transaction + Metervalues

### ISSUE THREAD

**Issue by rcuquemelle** [c-jimenez/open-ocpp-simu#2]
Bonjour,

Je me permets de vous contacter car j’utilise votre projet GitHub OCPP. Actuellement j’ai déployé le projet sur une Raspberry Pi et je voulais savoir pour la partie simulation en mqtt (open-ocpp-simu) si nous pouvons démarrer et arrêter une transaction et si il y a des envois de metervalues.
Merci pour votre aide et votre retour.

Cdt,

Romain

**Comment by c-jimenez** [comment]
Bonjour,

La partie simulation ne comporte que des simulateurs de bornes de recharge avec open-ocpp comme stack de communication OCPP.

[Le superviseur en python/MQTT](https://github.com/c-jimenez/open-ocpp-simu#usage) permet de piloter ces bornes simulées pour leur faire déclencher des charges et simuler des consommations de courant qui peuvent être remontées via des metervalues: CurrentImport, CurrentOffered, EnergyActiveImportRegister, PowerActiveImport et Voltage.

Par contre, la partie simulateur ne comprend pas de Central System (CSMS). Si vous voulez en mettre un en oeuvre très rapidement qui accepte toutes les demandes entrantes, je vous invite à vous baser sur l'exemple [quick start central system](https://github.com/c-jimenez/open-ocpp/blob/develop/examples/quick_start_centralsystem/README.md).

**Comment by rcuquemelle** [comment]
Bonjour,

Super c'est ce qu'on voulait mais comment fait on alors pour déclencher la charge et simuler une consommation de courant? Sur la partie graphique je ne vois pas comment cela se fait.

Merci d'avance.

Cdt,

Romain

**Comment by c-jimenez** [comment]
Bonjour,

Pour démarrer une charge depuis l'IHM du superviseur, il faut :

1. Mettre une résistance de cable via le slider "Car cable capacity" différente de 0 => le charge point devrait passer en "Preparing"
2. Rentrer un identifiant de badge dans le champs "Id Tag" puis cliquer sur "Pass" => la requête OCPP "Authorize" va être envoyée, si le CSMS accepte, alors la charge va commencer

Vous pouvez ensuite ajuster la simulation de charge consommée par le vehicule via le slider "Car consumption" et simuler une suspension/reprise de charge du véhicule par la checkbox "Car suspend".

Pour arrêter la charge, 2 possibilités :
- Mettre la résistance de cable à 0 (déconnexion véhicule)
- Repasser le même badge que celui utilisé au démarrage de la charge
