### ISSUE TITLE
Could not get RemoteStartTransaction working

### ISSUE THREAD

**Issue by angelorodem** [c-jimenez/open-ocpp-simu#24]
Hi, i have tried to start a remote transaction on this simulator, but it seems to not work or not be implemented,
i tried to send this message to the simulator,

`[2,1524699488,"RemoteStartTransaction",{"idTag":"free-tag","connectorId":1}]`

but it does not start the transaction when the CP is in Preparing or Available states.

This is the log that is dumped to the console when the CP receives the package:

```
Date time received : 2023-12-09T17:43:48Z
[  COM  ] - [2023-12-09T17:43:49] - ChargePoint.cpp:979 - RX : [2,1524699488,"RemoteStartTransaction",{"idTag":"free-tag","connectorId":1}]
[  COM  ] - [2023-12-09T17:43:49] - ChargePoint.cpp:986 - TX : [4, "", "ProtocolError", "", {}]
```

Note that the simulator works fine for authorizing with tags, but remote start seems to not be working, any tips?
Thanks!

**Comment by c-jimenez** [comment]
Hi,

The simulator implements the RemoteStart/Stop requests.

It seems that the format of your request is not valid : the unique id in the RPC frame must be a string. Here it as a raw integer : 1524699488.

The correct frame should be :

`[2,"1524699488","RemoteStartTransaction",{"idTag":"free-tag","connectorId":1}]`

Regards

**Comment by angelorodem** [comment]
You are correct, i wasn't aware of this, thanks alot!
